x-shared-config: &shared-config
  extra_hosts:
    - "wrenam.wrensecurity.local:10.0.0.11"
    - "wrenam1.wrensecurity.local:10.0.0.21"
    - "wrenam2.wrensecurity.local:10.0.0.22"
    - "wrends1.wrensecurity.local:10.0.0.31"
    - "ldap1.wrensecurity.local:10.0.0.41"

services:
  frontend:
    image: haproxy:2.7.8
    container_name: wrenam-frontend
    volumes:
      - .docker/frontend/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      wrenam:
        ipv4_address: 10.0.0.11
    <<: *shared-config

  wrenam1:
    image: "${WRENAM_IMAGE:-wrenam-test}"
    container_name: wrenam-test1
    hostname: wrenam1.wrensecurity.local
    entrypoint: "/srv/wrenam/entrypoint.sh"
    command: ["catalina.sh", "run"]
    volumes:
      - .docker/wrenam/entrypoint.sh:/srv/wrenam/entrypoint.sh:ro
      - .docker/wrenam/init1:/srv/wrenam/init
    depends_on:
      frontend:
        condition: service_started
      wrends1:
        condition: service_healthy
      ldap1:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth/isAlive.jsp"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 1m
      start_interval: 10s
    networks:
      wrenam:
        ipv4_address: 10.0.0.21
    <<: *shared-config

  wrenam2:
    image: "${WRENAM_IMAGE:-wrenam-test}"
    container_name: wrenam-test2
    hostname: wrenam2.wrensecurity.local
    volumes:
      - .docker/wrenam/config2.properties:/srv/wrenam/config.properties
    depends_on:
      frontend:
        condition: service_started
      wrends1:
        condition: service_healthy
      ldap1:
        condition: service_healthy
      wrenam1:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth/isAlive.jsp"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 1m
      start_interval: 10s
    networks:
      wrenam:
        ipv4_address: 10.0.0.22
    <<: *shared-config

  wrends1:
    image: wrensecurity/wrends:5.0.1
    container_name: wrenam-wrends1
    environment:
      BASE_DN: ou=wrenam,dc=wrensecurity,dc=org
      ROOT_USER_DN: cn=Directory Manager
      ROOT_USER_PASSWORD: password
    healthcheck:
      test: ["CMD", "curl", "-f", "ldap://localhost:1389"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 1m
      start_interval: 10s
    networks:
      wrenam:
        ipv4_address: 10.0.0.31
    <<: *shared-config

  ldap1:
    image: wrensecurity/wrends:5.0.1
    container_name: wrenam-ldap1
    environment:
      BASE_DN: dc=example,dc=org
    volumes:
      - .docker/userstore:/opt/wrends/bootstrap/init
    healthcheck:
      test: ["CMD", "curl", "-f", "ldap://localhost:1389"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 1m
      start_interval: 10s
    networks:
      wrenam:
        ipv4_address: 10.0.0.41
    <<: *shared-config

networks:
  wrenam:
    name: wrenam-test
    ipam:
      config:
        - subnet: 10.0.0.0/24
